name: CI

on: ["push", "pull_request"]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
        run: npm install

      - name: Linter
        run: npm run lint

      - name: Test
        run: npm test

      - name: Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        run: npm run coverage

      - name: Nightly Build
        run: npm run truffle:test
        env:
          SOLC_NIGHTLY: true
